terraform/modules/networking/variables.tf
terraform/modules/networking/vpc.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf
terraform/staging/variables.tf
terraform/test/main.tf
terraform/test/variables.tf

As mentioned on <https://digital.dclg.gov.uk/jira/browse/DT-23>
This is extra protection against misconfigured security groups, it is not supposed to replace them.
Allow:
* All egress, and ingress to ephemeral ports (>=1024) to allow replies back through (it's stateless)
* HTTPS
* HTTP
* SSH from allowed IPs
* ICMP because pinging things is useful sometimes
I've also just merged #17 which adds "Name" tags to the network resources that didn't have them already to make them easier to manage in the AWS console.

Restrict ingress on VPC default ACL

---

terraform/modules/jaspersoft/README.md
terraform/modules/jaspersoft/install_files/default_master.properties
terraform/modules/jaspersoft/instance.tf
terraform/modules/jaspersoft/jaspersoft_install_bucket.tf
terraform/modules/jaspersoft/setup_script.sh

It feels like there should be a better way to do this, but I couldn't find it.
This smooshes together 7.8.0, the 7.8.1 service pack, an updated Postgres driver and what I hope are the important bits of the hotfix. The hotfix is designed for the pro version and trying to apply the whole thing leaves you with a broken install.
I think it's worth considering putting this behind a login wall, once we have LDAP + KeyCloak that should be easy, and hopefully logging in twice with the same password isn't too big a deal.

Apply hotfix to Jaspersoft server

---

.github/workflows/roxy_deploy_marklogic_config.yml
terraform/modules/active_directory/README.md
terraform/modules/active_directory/management_server.tf
terraform/modules/active_directory/variables.tf
terraform/modules/active_directory_dns_resolver/main.tf
terraform/modules/github_runner/instance.tf
terraform/modules/github_runner/variables.tf
terraform/modules/jaspersoft/instance.tf
terraform/modules/jaspersoft/variables.tf
terraform/modules/marklogic/load_balancing.tf
terraform/modules/marklogic/variables.tf
terraform/modules/networking/outputs.tf
terraform/modules/networking/private_zone.tf
terraform/modules/networking/variables.tf
terraform/staging/main.tf
terraform/test/main.tf

This lets us simplify the roxy job since the MarkLogic NLB is now always at `marklogic.vpc.local`.

Private Route53 zone

---

.github/workflows/pull_requests.yml
README.md
manual_scripts/active_directory/groups.csv
manual_scripts/active_directory/users-to-groups.csv
manual_scripts/active_directory/users.csv
terraform/modules/jaspersoft/README.md
terraform/modules/jaspersoft/alb.tf
terraform/modules/jaspersoft/install_files/applicationContext-externalAuth-LDAP.xml
terraform/modules/jaspersoft/instance.tf
terraform/modules/jaspersoft/instance_profile.tf
terraform/modules/jaspersoft/jaspersoft_install_bucket.tf
terraform/modules/jaspersoft/setup_script.sh
terraform/modules/jaspersoft/variables.tf
terraform/staging/main.tf
terraform/test/main.tf

Differences from DataMart's staging setup:
* A new LDAP user (`jasperreports`) used for user and group lookups, rather than `superuser`
* Group membership lookup is transitive
* Membership of the `jasperreports-users` group is required to have any permissions, rather than all users having standard "ROLE_USER" permissions
* Admin permissions are granted only to a new group, `jasperreports-admins`, rather than to members of `datamart-delta-admin` (we could add that group to `jasperreports-admins` group if we want)
I've also added the web services plugin mentioned in Confluence [here](https://digital.dclg.gov.uk/confluence/display/DEL/Jaspersoft+Server+Upgrade), though haven't tried to use it, and fixed the health check endpoint for the ALB.
Note that user lookups are done by `cn`, not …

DT-66: LDAP for Jasper Reports server

---

terraform/modules/ses_identity/logs_query.tf

We've now got AWS accounts set up for the Delta internal support team. Adding a couple of simple queries to Terraform for them to use to see SES errors

Add Logs Insights saved query for SES

---

terraform/modules/networking/main.tf
terraform/modules/networking/outputs.tf
terraform/modules/networking/subnet.tf
terraform/modules/public_albs/main.tf
terraform/production/ecr.tf
terraform/production/main.tf
terraform/production/outputs.tf
terraform/staging/main.tf
terraform/staging/outputs.tf
terraform/test/main.tf
terraform/test/outputs.tf

Moved the auth alb listener to common infrastructure from delta since both auth service and keycloak will need to use it now
Created ECR repo and subnets for auth service.

DT 460: setting up auth service terraform

---

terraform/modules/marklogic/app_logs.tf
terraform/modules/marklogic/scripted_metrics.tf
terraform/modules/marklogic/scripts/metrics-cron.sh
terraform/modules/marklogic/scripts/metrics-json.xqy
terraform/modules/marklogic/templates/metrics_config_ssm_doc.yml

* Systems Manager to set up a cron job on the master MarkLogic node only (x.x.12.x)
* This posts an XQuery script to be evaluated which gathers metrics and returns them as JSON, e.g.
```json
{"metric": "task-server-total-queue-size", "value": 20}
```
* The cron script gets them into a format CloudWatch expects and then does put-log-events via the CLI
* A metric filter turns those into CloudWatch metrics so we can graph + alarm on them (though I haven't done that yet)
Other options would be putting metric data directly, or sending embedded metric format logs to the CloudWatch agent, but this seemed simplest and works OK.

DT-294 Scripted metrics from MarkLogic

---

terraform/modules/cloudfront_distributions/keycloak_function.tf
terraform/modules/cloudfront_distributions/main.tf
terraform/modules/cloudfront_distributions/output.tf
terraform/modules/cloudfront_distributions/variables.tf
terraform/modules/public_albs/auth_listener.tf
terraform/modules/waf/main.tf
terraform/modules/waf/variables.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/test/main.tf

The auth service is now at the root of the auth domain, Keycloak is only at `/keycloak`. Apply the IP restriction to that path only. Also rename the CloudFront distribution within Terraform from "keycloak" to "auth", but not on CloudFront itself.
Edit: Turns out WAF happens before the rewriter lambda, will need to cover those paths too - done

DT-518 Make auth WAF IP restriction keycloak-only

---

terraform/modules/marklogic/backup_buckets_new.tf
terraform/modules/s3_bucket/main.tf

It's not supported: https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html

Disable KMS encryption for access log target buckets

---

terraform/production/datamart_imported_logs.tf

Create a bucket and grant the Datamart AWS account access to it through the bucket policy, with the restriction that they can only PutObject straight to the GLACIER (Glacier Flexible Retrieval) storage class, e.g.
```sh
aws s3 cp a-file s3://dluhc-datamart-imported-logs-production/a-file --storage-class GLACIER
```
I've already applied this, so if we're happy with it we can give Digital Space the bucket name.

DT-227 Create S3 bucket for imported Datamart logs

---

terraform/modules/cloudfront_distributions/main.tf
terraform/modules/cloudfront_distributions/variables.tf
terraform/production/main.tf
terraform/staging/main.tf

Having the geo-restriction completely disabled for the auth service isn't ideal, but it's currently open due to Home Connections non-UK IP.
Home Connection's IPs all come up as US currently https://www.maxmind.com/en/geoip2-precision-demo so I've added that to the list.
We'll need to co-ordinate with them to test it when we release this.

DT-335 Update geo-restriction for API and Auth service

---

terraform/modules/networking/firewall_monitoring.tf
terraform/modules/networking/variables.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/test/main.tf

Update packets dropped alarm to go to security sns topic rather than metric one
(successfully applied to test but not tested in any way)

Update packets dropped alarm to go to security sns topic

---

terraform/production/main.tf

Home connections have said they can still communicate with the staging API, so should be good to restrict prod too

DT-525 Update geo location restriction for auth service

---

terraform/modules/cloudfront_alb_monitoring/main.tf

I'm ignoring it when it goes off, assuming everyone else is too we should increase the threshold

Increase threshold for delta website client error rate

---

terraform/production/main.tf

Doesn't really matter because there's an IP allowlist, but should mean bots from other countries stop setting off the WAF alarm.
Staging is already IP restricted in this way, as is production Keycloak/auth service.

IP restrict production API

---

terraform/modules/backup_replication_bucket/main.tf
terraform/modules/marklogic/backup_buckets.tf
terraform/modules/marklogic/backup_replication.tf
terraform/modules/marklogic/marklogic_iam.tf
terraform/modules/marklogic/monitoring_dashboard.tf
terraform/modules/marklogic/variables.tf
terraform/modules/marklogic_restore_rehearsal/marklogic_iam.tf
terraform/modules/marklogic_restore_rehearsal/variables.tf
terraform/modules/notifications/main.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/test/main.tf

New bucket to replicate weekly backups to with Object Lock enabled.
* MarkLogic 10 can't write backups directly to a bucket with Object Lock enabled, so instead I've made another bucket that can be replicated to
* This is an annoying extra step, but should mean less work if we ever separate the replicated backup into another AWS account, which we'd like to do at some point anyway
* I've put the replication bucket in the same region as the main one, should we move it to London? S3 Ireland becoming unavailable seems pretty unlikely, but it should be easy to do
* I've tested backing up to the weekly bucket and then restoring from the replica bucket (payments-content on test)
* Added a notification for replication failure, though haven't tested it
* Only new files are replicated, existing …

DT-742 Create Object Locked backup bucket

---

terraform/modules/notifications/main.tf

Turns out alarms haven't been working since we applied the recent SNS topic changes. I got someone to test GuardDuty, but didn't think to test the alarms themselves...
It doesn't look like there's any risky changes pending so I'll deploy this straight through to production once it's merged.

Fix SNS policies to allow CloudWatch alarms

---

terraform/modules/marklogic/monitoring_alarms.tf
terraform/modules/marklogic/templates/metrics_config_ssm_doc.yml

These have been broken in all three environments since the update. The setup script failed to create the log group as `jq` wasn't installed, presumably because the user data script hadn't finished installing it yet. I've added a wait command, though haven't tried recreating any ML instances. AWS RunCommand ignores return codes so it looks like it succeeded.
The alarms didn't have insufficient_data actions, so we didn't get notified of the problem.

Fix ML metrics

---

terraform/modules/marklogic/check_forest_state.sh
terraform/modules/marklogic/final_forest_state.sh
terraform/modules/marklogic/restart_server.sh

The maintenance window log was filled up with curl progress this morning when test ML was broken.

Add silent flag to curl commands in ML patching scripts

---

terraform/modules/cloudfront_alb_monitoring/main.tf
terraform/modules/cloudfront_alb_monitoring_instance/alb_alarms.tf

https://softwire.slack.com/archives/C05A1E36GNP/p1710249640029849
Making the alarm less sensitive due to orbeon sending requests when someone is on the orbeon page but has timed out

Increase threshold for alb target client error rate alarm

---

terraform/modules/iam_roles/outputs.tf
terraform/modules/iam_roles/policies.tf
terraform/production/outputs.tf
terraform/staging/outputs.tf
terraform/test/outputs.tf

For https://github.com/communitiesuk/delta/pull/1448.
Only production actually needs the output for now, but I figured may as well keep them consistent.

Prevent CodeArtifact delete and export infra support role name

---

terraform/modules/ebs_backup/outputs.tf
terraform/modules/ebs_backup/role.tf
terraform/modules/ebs_backup/sns.tf
terraform/modules/ebs_backup/variables.tf
terraform/modules/marklogic/ebs_backup.tf
terraform/modules/marklogic/variables.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/test/main.tf

In preparation for sharing them with a new AWS Backup Vault for the new system volume backups.
This replaces the current MarkLogic-specific SNS topic, so we'll need to confirm the new subscription (which I've done for test)

DT-371 Move EBS backup role and SNS topic to separate module

---

terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf

We no longer own `dluhc-preprod.uk`. It was only referenced by the bastion host anyway.
I haven't tried applying this since it's prod.
We should manually delete the hosted zone when this is released.

DT-997 Remove dluhc-preprod.uk as secondary domain for bastion

---

terraform/modules/marklogic/backup_buckets.tf
terraform/production/main.tf
terraform/staging/main.tf

* Reduce the retention for the weekly backup source bucket as it should be replicated and we don't want to keep two copies 💸 
* Increase the object lock period on the replicated bucket, we're reasonably confident it works now
I'm reasonably sure this won't delete the objects in the bucket we replicate too:
> if lifecycle configuration is enabled only on your source bucket, Amazon S3 creates delete markers for expired objects but doesn't replicate those markers
<https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-what-is-isnot-replicated.html#replication-delete-op>
But we should keep an eye out on staging.

DT-803 Update backup retention for weekly buckets

---

terraform/modules/marklogic/backup_buckets.tf
terraform/modules/marklogic/variables.tf
terraform/production/main.tf

So that we can release this without having had a chance to thoroughly test it on staging. 60 is somewhat arbitrary, but if this somehow causes the replicated backups to be deleted it's enough history to keep (was originally 90 days).
I haven't tested or applied this anywhere, it should only affect production.

DT-803: Set weekly source backup retention to 60 days on production

---

terraform/modules/iam_roles/policies.tf

Since manually triggering one for Orbeon is part of the release process. I've checked it works on test.

Give infra support permissions for autoscaling group instance refreshes

---

terraform/modules/networking/ecr_interfaces.tf
terraform/modules/networking/main.tf
terraform/production/ecr.tf
terraform/staging/ecr.tf

ECR pull through cache rule so that access to ECR public (which needs *.cloudfront.net to be allowlisted to work 🤦) isn't required from within the VPC, plus associated changes to the VPC interface permissions.
Allow access to X-Ray from the auth service, I don't think there's any reason to use a VPC interface endpoint over allowing it through the firewall.

DT-732 Changes required for auth service telemetry

---

terraform/modules/networking/main.tf

So the delta-marklogic-deploy jobs can use OIDC to authenticate to AWS

DT-753 Add sts to TLS allowlist for github runner

---

manual_scripts/active_directory/users-to-groups.csv
manual_scripts/active_directory/users.csv
terraform/modules/networking/main.tf
terraform/modules/networking/outputs.tf
terraform/modules/networking/subnet.tf
terraform/production/outputs.tf
terraform/staging/outputs.tf
terraform/test/outputs.tf

Turns out it's used by fo-to-pdf so rename instead of removing. Will need a corresponding change in the Delta terraform, but I've left both outputs for now so it doesn't need to be done in order.
It will destroy and recreate the route tables with the new names, so technically this comes with downtime for fo-to-pdf, but it should only be a couple of seconds.
I've also removed reference to the deltainternal AD user, if it hasn't already I'll remove it from all environments when this is merged.

DT-1100 Rename "internal" subnet to fo-to-pdf

---

terraform/modules/cloudfront_alb_monitoring/main.tf

The default is 30. The recent API issue would be the only time this would have gone off in the last 4 weeks.
Also increase the % threshold for the website, Orbeon keeps setting it off.

Increase sensitivity of auth client errors alarm

---

terraform/modules/marklogic/deploy_user.tf
terraform/modules/marklogic/outputs.tf
terraform/modules/marklogic/variables.tf
terraform/modules/ses_user/main.tf
terraform/modules/ses_user/secret.tf
terraform/production/main.tf
terraform/production/outputs.tf
terraform/staging/main.tf
terraform/staging/outputs.tf
terraform/test/main.tf

DT-280 SES users are now encrypted with keys specific to Delta and CPM.
Opening this PR for you, because you moved the ticket to ready for review but didn't create a PR?

DT-280 Change SES to use keys specific to application

---

terraform/modules/marklogic/dap_export_s3.tf
terraform/modules/marklogic/variables.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf
terraform/staging/variables.tf
terraform/test/main.tf
terraform/test/variables.tf

Allowing Funding service Find team read only access to staging DAP export S3 bucket.

DT-1395: Sharing staging S3 DAP bucket with Funding Service Find team
