communitiesuk/delta-common-infrastructure

.github/workflows/terraform.yml
terraform/modules/networking/outputs.tf
terraform/modules/networking/route_table.tf
terraform/modules/networking/subnet.tf
terraform/modules/networking/variables.tf

These are /24 rather than /20, might be worth shrinking the other as well.

Add public subnets for ALBs

---

terraform/modules/cloudfront/cloudfront-waf.tf
terraform/modules/cloudfront/cloudfront.tf

Been meaning to get around to this, seems to work fine.

Switch to WAFv2 and managed rules

---

terraform/modules/github_runner/README.md
terraform/modules/github_runner/scripts/instance_user_data.sh
terraform/modules/networking/cloudwatch_interfaces.tf
terraform/modules/networking/ec2_api_interface.tf
terraform/modules/networking/main.tf
terraform/modules/networking/outputs.tf
terraform/modules/networking/secrets_manager_interface.tf
terraform/modules/networking/ssm_interfaces.tf
terraform/modules/networking/subnet.tf
terraform/staging/main.tf

Move the GitHub runner instance to its own subnet and configure the required VPC endpoints and firewall rules.
The VPC Interface Endpoints are about $8/month each, so shouldn't add up to too much even though we need a few of them.

DT-23 Firewall for GitHub runner

---

README.md
terraform/modules/active_directory/README.md
terraform/modules/active_directory/management_server.tf
terraform/modules/jaspersoft/backup.tf
terraform/modules/jaspersoft/jaspersoft_install_bucket.tf
terraform/modules/jaspersoft/variables.tf
terraform/staging/main.tf
terraform/staging/outputs.tf
terraform/staging/variables.tf
terraform/test/main.tf
terraform/test/outputs.tf
terraform/test/variables.tf

I've also rearranged the main.tf files so the modules are in the order they need to be created/should only have dependencies going one way.

Add Jaspersoft to staging and apply AD DNS changes to test environment

---

terraform/modules/active_directory/README.md
terraform/modules/active_directory/ca_server.tf
terraform/modules/active_directory/managed_ad.tf
terraform/modules/active_directory/outputs.tf
terraform/modules/active_directory/security_groups.tf
terraform/modules/active_directory/variables.tf
terraform/modules/networking/route_table.tf
terraform/modules/networking/variables.tf
terraform/modules/networking/vpc.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/staging/vpc_peer.tf
terraform/test/main.tf
terraform/test/vpc_peer.tf

Experimenting peering the test and staging VPCs with test pretending to be Datamart.
~Not necessarily intending to merge this, just putting it up so it's visible.~ On second thoughts I would like to merge it, having unmerged changes is annoying with terraform

Experiment: Peer staging and test VPCs

---

manual_scripts/active_directory/users.csv

DT-42: Add service user for Keycloak

---

terraform/modules/networking/main.tf

AD Management Server now has access to Directory Services (ds). Access directly through firewall, no endpoint.

Fix domain join blocked by firewall

---

terraform/modules/cloudfront_distributions/keycloak_function.tf

See https://github.com/communitiesuk/delta/pull/1102

DT-480 Update CloudFront function to send requests to new Keycloak path

---

terraform/modules/marklogic/scripts/metrics-json.xqy

Will be good to have alarms on these

Add metric for minutes since last backup

---

terraform/modules/s3_bucket/main.tf
terraform/modules/s3_bucket/variables.tf

Adding object lock option to s3 bucket code to allow usage in [DT-503](https://dluhcdigital.atlassian.net/browse/DT-503).

DT-503 add object lock option

---

manual_scripts/active_directory/generate-more-users.ps1

This PR is just for generating users.
Separately, to add form data, the plan is:
* Create a copy of the h-clic form + dataset + instance, open for the next few decades.
* Upload a million submissions. We may need to do this with a marklogic script

DT-605: script for adding users

---

terraform/modules/cloudfront_distributions/main.tf
terraform/modules/cloudfront_distributions/variables.tf
terraform/modules/waf/main.tf
terraform/modules/waf/monitoring.tf
terraform/modules/waf/variables.tf
terraform/test/main.tf

Replaced by application level rate limiting in the auth service

Remove WAF login rate limit

---

terraform/production/main.tf

I'll raise a ticket to re-enable

Disable production ML patching maintenance window

---

terraform/modules/cloudfront_website/main.tf

DT-887 Cache /delta_assets/ path at CloudFront

---

terraform/modules/iam_roles/policies.tf

To reduce number of errors when viewing the suppression list

Grant cloudwatch monitor and app support ses:GetAccount

---

terraform/modules/ses_identity/variables.tf
terraform/production/main.tf
terraform/staging/main.tf
terraform/test/main.tf

Remove unused bounce_complaint_notification_emails

---

terraform/modules/cloudfront_website/503.html
terraform/modules/cloudfront_website/error.html

Only two to update in this repo 🎉

DT-982: update static error pages

---

terraform/production/main.tf

Have shared mailbox to use instead now

Remove Yousuf from notification emails

---

manual_scripts/active_directory/get_access_groups.ps1

Script prepared by @hugh-emerson

Added script used to manually get access group information from AD server

---

terraform/modules/marklogic/dap_export_s3.tf

Added ListBucket permission for DAP export external access

DT-1395: Use ListBucket permission for DAP export external access

---

terraform/modules/bastion_host/instance.tf

I've applied to staging and it seems to work

DT-1476: change bastion server to AL2023 instead of Amazon Linux 2

---

terraform/backend/main.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf
terraform/staging/variables.tf
terraform/test/main.tf
terraform/test/variables.tf

Removed softwire emails from notification emails and other properties
No local testing available

DT-1696: Removed softwire emails
